name: Set change logs on a pull request comment

on:
  pull_request:
    branches: 
      - 'master'
      - '*/master'
      - 'demo'
      - '*/demo'

jobs:
  build:
    name: Set change logs on a pull request comment
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Get base branch name
        id: base_branch
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: | 
            const { ref } = context.payload.pull_request.base;
            console.log(ref)
            return ref

      - name: Get current branch name
        id: head_branch
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: | 
            const { ref } = context.payload.pull_request.head;
            console.log(ref)
            return ref

      - name: Get pull request number
        id: pull_request_number
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: | 
            const { number } = context.payload.pull_request;
            console.log(number)
            return number
          
      - name: Get related release list
        id: tag_list
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: | 
            const script = require(`${process.env.GITHUB_WORKSPACE}/actions/getRelatedReleaseList.js`)
            return script({context, github} ,${{ steps.base_branch.outputs.result }})

      - name: Set npx command of github-changes
        id: npx_command
        uses: actions/github-script@v3
        with:
          result-encoding: string
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: | 
            const tagList = ${{ steps.tag_list.outputs.result }}
            // 同じbaseブランチで発行されたreleaseがない場合は全てのログを出力し、ある場合は最後のrelease以降のログのみ出力する。
            if(tagList.length === 0) {
              return 'npx github-changes -o ${{ github.repository_owner }} -r ${{ github.event.repository.name }} --hide-tag-names --only-pulls --use-commit-body -z Asia/Tokyo -k ${{ github.token }} -b ${{ steps.head_branch.outputs.result }}'
            } else {
              return `npx github-changes -o ${{ github.repository_owner }} -r ${{ github.event.repository.name }} --hide-tag-names --only-pulls --use-commit-body -z Asia/Tokyo -k ${{ github.token }} -b ${{ steps.head_branch.outputs.result }} --between-tags ${tagList[0].tag_name} ...`
            }

      - name: Run github-changes and create the change log file
        uses: actions/setup-node@v1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm i -D github-changes
      - run: ${{ steps.npx_command.outputs.result }}

      - name: Cat the change log file and format output
        id: log
        run: |
          # 整形しないと最初の一行しか取得できないので、一度変数に入れたあとに成形する
          LOG="$(cat CHANGELOG.md)"
          LOG="${LOG//'%'/'%25'}"
          LOG="${LOG//$'\n'/'%0A'}"
          LOG="${LOG//$'\r'/'%0D'}"
          echo "::set-output name=LOG::$LOG"

      - name: Set change logs on a pull request comment 
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: | 
            const script = require(`${process.env.GITHUB_WORKSPACE}/actions/setChangeLogsOnAPullRequestComment.js`)
            script({context, github}, ${{ steps.pull_request_number.outputs.result }}, ${{ toJson(steps.log.outputs.log) }})
            

